apiVersion: v1
kind: Service
metadata:
  name: minecraftservice
spec:
  type: LoadBalancer
  ports:
  - port: 25565
    targetPort: 25565
    protocol: TCP
  selector:
    app: minecraftservice