apiVersion: v1
kind: Service
metadata:
  name: minecraftservice
spec:
  type: LoadBalancer
  ports:
  - name: connect
    port: 25565
    targetPort: 25565
    protocol: TCP
  - name: rcon 
    port: 25575
    targetPort: 25575
    protocol: TCP
  selector:
    app: minecraftservice