apiVersion: apps/v1
kind: Deployment
metadata:
  name: csminecraft
  labels:
    app: minecraftservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: minecraftservice
  template:
    metadata:
      labels:
        app: minecraftservice
    spec:
      containers:
      - name: portal-minecraft
        image: openhack/minecraft-server:2.0
        ports:
        - containerPort: 25565
          hostPort: 25565
        env:
        - name: EULA
          value: "true"
        volumeMounts:
        - mountPath: "/data"
          name: volume
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: minecraftazuredisk